version: '3'

services:
  database:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=DB
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

  backend:
    image: racs0/so1_back_jun2024_p16:1.0.0
    privileged: true
    pid: host
    container_name: backend_container
    env_file: .env
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: /proc
        target: /proc
    restart: always
    depends_on:
      - database
    networks:
      - app-network
    cap_add:
      - SYS_MODULE
      - SYS_ADMIN
      - NET_ADMIN

  frontend:
    image: racs0/so1_front_jun2024_p16:1.0.0
    container_name: front_container
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    external: false