apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: so1-proyecto2-ingress
  namespace: so1jun2024
spec:
  ingressClassName: nginx
  rules:
    - host: 34.122.71.194.nip.io
      http:
        paths:
          - path: /insert
            pathType: Prefix
            backend:
              service:
                name: grpc-client-service
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3100

